---
# tasks file for roles/proxy
- name: Run NGINX reverse proxy
  docker_container:
    name: my-proxy
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - name: my-app-network
    state: started
    restart_policy: always
